### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by ultrasam** [ukdtom/ClaimIt#10]
I am getting this error when trying to execute the script

./claimpms.sh: 17: ./claimpms.sh: Syntax error: "(" unexpected

**Comment by ultrasam** [comment]
I managed to fix this by using:

bash claimpms.sh

but now it gave me this

![image](https://user-images.githubusercontent.com/688251/56866829-a1ffea80-69a3-11e9-9d5a-6942bb6e0012.png)

**Comment by ukdtom** [comment]
Check you preferences.xml file in PMS

Also, if using a public IP Address, which I assume you are, since you blanked it out, use 127.0.0.1 for IP Address, and see if that helps

**Comment by ukdtom** [comment]
And just created this Wiki page

https://github.com/ukdtom/ClaimIt/wiki/Error-running-this

**Comment by ukdtom** [comment]
Ping

**Comment by ukdtom** [comment]
Closed due to lack of response
