### ISSUE TITLE
HTTP error 500

### ISSUE THREAD

**Issue by the-germ** [ukdtom/ClaimIt#12]
I had error 401 and I followed the instructions at plex.tv to remove the lines from Preferences.xml.
The I restarted my Linux box and my PC. Now I get error 500

![image](https://user-images.githubusercontent.com/50252997/57170629-796b6b00-6e51-11e9-9edf-e0dee559fe16.png)

any ideas? I realise that 500 is generic error, but I really have no idea. I have Apache2 on the same server as PMS so is it my web server that's returning the 500 or something else. Is there anything I can do to track the problem down.
Thanks
the-germ

**Comment by ukdtom** [comment]
Error 500 means internal error, and is most likely issued by your PMS for some reason.

Maybe PMS logs will show what's going on?

**Comment by ukdtom** [comment]
Or you broke your prefs.xml file?

**Comment by the-germ** [comment]
Thanks for your response ukdtom. 
I did check the permissions on pref.xml after editing but I forgot about file ownership. However that didn't fix it anyway. My next step is to double check the contents of prefs.xml but its late for me, so that will be tomorrow if I have time.

There is a lot of info in the log file, but I'm sure if any of it is relevant to my problem.

**Comment by ukdtom** [comment]
Remember to restart PMS after changing ownership!

**Comment by the-germ** [comment]
I did a re-install of the PMS and I still get the 500 Error. The log file contain lots of this error
ERROR - Error issuing curl_easy_perform(handle): 28
and I have just realized that there is an "Error parsing XML" as well, but it gives no indication as to what might be wrong with the XML.

**Comment by ukdtom** [comment]
Sadly hard to help here, without the logs and the XML

**Comment by the-germ** [comment]
unfortunately I suffered a disk failure which I had to a complete re-install of my server and now Plex has found the server and all my media. 
Thanks for the help I received here anyway.
