### ISSUE TITLE
Need a better IP Address input box in Windows program

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/ClaimIt#14]
This is just a reminder that a better IP Address input box is needed for the Windows program.

The current box is somewhat confusing for inexperienced users.

**Comment by nicaruspl** [comment]
Mask for mtbIPAddress depends on regional settings.
User should change regional settings or change in Form1.cs 
from 
PMSIPAddr = mtbIPAddress.Text.Replace(" ", "");
to
PMSIPAddr = mtbIPAddress.Text.Replace(" ", "").Replace(",",".");
![Mask preview](https://user-images.githubusercontent.com/40137148/58762198-ec99f700-854d-11e9-821a-1a4415c83a27.png)

**Comment by Modiete** [comment]
I'm having problems entering my NAS IP, could someone help me tell me how should i do it?

The IP of my NAS is 192.168.1.9

And it keep saying:

![imagen](https://user-images.githubusercontent.com/80482466/110837618-bdc3bf80-82a1-11eb-8516-7760e9faadbd.png)

Same result if enter 192.168.1.9 (without 0s) or 192.168.1.009

I know it's a noob question but.. i don't know how to enter my IP

Could someone help me please?

**Comment by proimage** [comment]
> I'm having problems entering my NAS IP, could someone help me tell me how should i do it?
> I know it's a noob question but.. i don't know how to enter my IP
> 
> Could someone help me please?

Try adding a space when there's not three digits to provide. So, `192.168.[space][space]1.[space][space]9`.

**Comment by ukdtom** [comment]
Windows version has been replaced with this one:

https://github.com/ukdtom/ClaimPMS4Win/releases/latest
