### ISSUE TITLE
Syntax Error Claimpms ReadyNas

### ISSUE THREAD

**Issue by fryc88** [ukdtom/ClaimIt#15]
root@FryC-RN204:/tmp# ./claimpms.sh
./claimpms.sh: line 7: syntax error near unexpected token `newline'
./claimpms.sh: line 7: `<!DOCTYPE html>'

Same when i start as bash:
root@FryC-RN204:/tmp# bash claimpms.sh
claimpms.sh: line 7: syntax error near unexpected token `newline'
claimpms.sh: line 7: `<!DOCTYPE html>'

Thats what i've got after trying to start it on Netgear Readynas. 
Any clues? Please...I'm trying to get it working for last 2 weeks, without success.
NAS have public IP address 91.*.*.* set up, it is connected straight to internet, without routers, NAT, etc.
All the time looking for servers, so claimpms is my last hope :)

**Comment by ziggimon** [comment]
Any chance your running the script on Ubuntu or the likes where /bin/sh is symlinked to dash? So it doesn't understand the defined functions.

Try running it in this way: bash ./claimpms.sh

**Comment by fryc88** [comment]
Yeah it was already done, it gave me same output, then checked claimpms.sh and it was messed up inside, so redownloaded it, started again, and now im stuck at entering my details lol.

******** ERROR ********
We failed to authenticate towards plex.tv
Please check username and password, as well as network access


Does the script supports special characters in passwords like $%&* ?? Because using my details i can normally login on plex.tv but not working in script.

**Comment by fryc88** [comment]
Yeah definitely script is not supporting special characters. Changed password, got output as below, but server is still looking for servers...


> ************************************************************************
> * Script to claim a Plex Media Server
> * Will prompt for
> *     * plex.tv username
> *     * plex.tv password
> *     * IP Address of your unclaimed Plex Media Server
> *
> *
> * Made by dane22, a Plex community member
> * And Mark Walker/ZiGGiMoN, a Plex hobbyist
> *
> * Version 1.1.0.0
> *
> * To see the manual, please visit https://github.com/ukdtom/ClaimIt/wiki
> ************************************************************************
> plex.tv Username: ****
> 
> plex.tv Password:
> plex.tv Password Repeated:
> IP Address of PMS server: 127.0.0.1
> Comparing entered passwords
> Comparing entered passwords ok
> Validating IP address
> Getting PMS Server Identifier
> Getting PMS Server Identifier ok
> Getting User Token from plex.tv
> Getting User Token from plex.tv ok
> Getting PMS Claim Token
> Getting PMS Claim Token ok
> Claiming server
> Claiming server ok 200
> 
> 
> Please close your browser, reopen, and browse to http://127.0.0.1:32400/web
>

**Comment by ziggimon** [comment]
I'm looking into the special char issue.

You could ssh tunnel into the NAS to forward port 32400 and access it locally, but once claimed your user should be able to access it. Unless it's not being published correctly.

Can you access: http://PublicIP:32400/web while logged in to plex.tv as your current user.

**Comment by fryc88** [comment]
At this moment, when i login to plex.tv, and then go to http://mypublicip:32400/web it is acting like before, just looking for servers and starts as client instead of server...
I even removed PMS, deleted config files, installed from scratch and again run script - same problem after, starts as client instead of server.

**Comment by ziggimon** [comment]
Does it find the server if you tunnel port 32400 to the device and grab the page locally over ssh ?

**Comment by fryc88** [comment]
Tbh i'm not sure how to use tunnel properly...

> ssh -R 32401:127.0.0.1:32400 public.ip.of.my.nas

I ran it but does not look like it is working, and now i cannot start any other tunnel, it just hangs my terminal connection when i put anything else...

**Comment by ziggimon** [comment]
Should be: ssh -L 32401:127.0.0.1:32400 public.ip.of.my.nas

Then access http://127.0.0.1:32401/web

**Comment by fryc88** [comment]
Alright, but how do i remove it now, it told me before it was added permamently to something, and now it does not start at all when i run new command to forward anything else :/

**Comment by ziggimon** [comment]
To stop a local forward you just exit your ssh session. The ssh before could have been prompting you to yes/no your hostkey entry, though this has nothing to do with the forward. To remove a hostkey entry run: ssh-keygen -f "~/.ssh/known_hosts" -R public.ip.of.my.nas

What new commands are you running?

**Comment by fryc88** [comment]
To clear out situation.
- my nas have different public ip starting 91.*.*.*
- have it filled in network settings, connected straight to internet
- i'm in different location, different network, with public ip starting 151.*.*.*, so filling 127.0.0.1 into my browser won't work.

Do you mean i can forward localhost port just to outside, to access it now from my computer or what? Because now im bit confused, and after forwarding it i still cannot access it through my computer when i pop ip 91.*.*.*:32402/web

**Comment by ziggimon** [comment]
It does if you do the SSH tunneling. Thus the: ssh -L 32401:127.0.0.1:32400 public.ip.oc.my.nas

Once the ssh connection is open you should be able to access: https://127.0.0.1:32401/web

Its important the ssh connection is established when doing so.

**Comment by fryc88** [comment]
It is not opening anything in my browser, not as https://127.0.0.1:32401/web (which is still unclear why should i use localhost ip on other device) and not as https://91.*.*.*:32401/web
Browsers gives me just timeout.

**Comment by ziggimon** [comment]
If your tunneling the way you started, its https://127.0.0.1:32401/web locally, and https://91.*.*.*:32400/web not on port 32401 unless you have some firewall in the remote end set to forward port 32400 on the NAS to port 32401 on the external side.

Is Plex Media Server running on the NAS when you get the timeouts.

**Comment by fryc88** [comment]
Yes, PMS works on nas when i got timeout.
I still have no idea why on my computer should i input localhost ip to connect to different network nas, sorry.
There is no firewall, nothig which could block port or connection at this moment.

**Comment by ziggimon** [comment]
Try reading over the "On a Different Network" section on remote connection and ssh tunneling:

https://support.plex.tv/articles/200288586-installation/

**Comment by fryc88** [comment]
Ok, now i understand. I'm using Windows on my computer and been starting tunneling from ssh on my NAS...
So i've done tunnel through Putty now, and when i go to http://localhost:8888/web i've got 'invalid request' in my browser...

**Comment by fryc88** [comment]
Yeah now i can log in, but does the same, looking for servers lol...

**Comment by fryc88** [comment]
Still same, removed everything, removed config, installed again from scratch, ran script, then open tunnel, run in browser - asks for login details so i put same as in script, then looking for servers :/

**Comment by ukdtom** [comment]
Since your server was claimed by our script, maybe this is a better url to use:
https://app.plex.tv/desktop

**Comment by fryc88** [comment]
When i go there, also tells me the same, looking for servers.
I think it could be some internal prob with PMS, because i can't see any other options at this moment, unless you guys have some more suggestions.

**Comment by ukdtom** [comment]
Are you using jumbo frames on your NIC?

**Comment by fryc88** [comment]
I dont know to be honest, never set it up, never changed it so if it is off by default then probably I dont use it.

**Comment by ukdtom** [comment]
Are there a FW on the box, and if so, could you try and disable it for a short test, and after that, restart PMS

**Comment by fryc88** [comment]
Could you please explain first part? My English is not rly perfect so i

**Comment by ukdtom** [comment]
FW = Firewall

**Comment by fryc88** [comment]
MTU is set to 1500 on my NAS.

**Comment by ukdtom** [comment]
Then not using Jumbo Frames, which is good, so what about the Firewall?

**Comment by fryc88** [comment]
I don't see any issues with firewall, on NAS-side i would say there is kind of no firewall blocking it.

**Comment by ukdtom** [comment]
Then I've sadly no more ideas, but is about 99.9% sure you have some kinda networking issue

Sadly not a ReadyNas dude, so can't assist further, and can only suggest you try the forums

**Comment by fryc88** [comment]
Thank you both guys for your time and patience anyway.
I think ill just migrate to other system, as it is not so powerful anyway to transcode 2-3 1080p videos at same time.
Just spoken with friend and will get his HP Microserver gen8 instead probalby, so depends of software what ill choose on it should be fine i hope.
In the meantime ill try to connect it through server so it will obtain 172.x.x.x ip address and get it redirected to public, i dont really like this way, but oh well...
