### ISSUE TITLE
Idle....

### ISSUE THREAD

**Issue by koelner21** [ukdtom/ClaimIt#18]
LOGIN: Thunderdome##  BENUTZERNAME: 
Passwort: ####
Passwort: ####
IP: 192.168.178.77

Nothing happened.

Windows 10 Installation

**Comment by ukdtom** [comment]
Screendump please, and if running on the PMS server itself, use 127.0.0.1 as IP Address

**Comment by koelner21** [comment]
![image](https://user-images.githubusercontent.com/3396639/61005365-5df87100-a368-11e9-99a1-aa3befbc1e60.png)

Do you mean this?

**Comment by koelner21** [comment]
I have a Synology 418pla I startet the Programm from windows, because i dont know how it works on NAS

**Comment by ukdtom** [comment]
What's the IP address of your workstation?

**Comment by koelner21** [comment]
![image](https://user-images.githubusercontent.com/3396639/61005638-de1ed680-a368-11e9-8e6a-a23af95b0498.png)

Do you mean this one?

**Comment by ukdtom** [comment]
If above is your IP address of your windows box, then you must write the IP address of your Syno box, where PMS runs

**Comment by ukdtom** [comment]
And you did press the ClaimIt button ?

**Comment by koelner21** [comment]
Yes. i but the Button.... But then this MEssage comes:

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei ClaimIt.Form1.<>c.<_IsPrivate>b__40_0(String s)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei ClaimIt.Form1._IsPrivate(String ipAddress)
   bei ClaimIt.Form1.BtnClaimIt_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3416.0 built by: NET472REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
ClaimIt
    Assembly-Version: 1.1.0.0.
    Win32-Version: 1.1.0.0.
    CodeBase: file://INDIVIDUALIST/public/ClaimIt-1.1.0.0/Windows/ClaimIt/ClaimIt.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3324.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3416.0 built by: NET472REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3429.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by koelner21** [comment]
![image](https://user-images.githubusercontent.com/3396639/61006039-af553000-a369-11e9-8cd5-a8a71cf595a7.png)

This is from my Router, there you can see, that i take the IP from my Synology

**Comment by ukdtom** [comment]
Thanks for the error msg....

It says the IP address you entered is in the wrong format, and hard to see on the screendump, but is it a dot between the numbers, or a comma?

**Comment by ukdtom** [comment]
It has to be a dot

**Comment by koelner21** [comment]
I had the same idea, so i copy it, but it wont work

**Comment by ukdtom** [comment]
I'll have to try and reproduce, but sadly sidetracked with other work the next couple of days, so sadly it'll take until then

**Comment by koelner21** [comment]
No problem .. I do not know if it really helps me. I have problems with the remote connection, although the server tells me it would work.

**Comment by ukdtom** [comment]
Remote connections has nothing to do with this plugin, if server is claimed!

**Comment by koelner21** [comment]
I found this one...

Q16: Searching for server, how can I connect to the server?

Important: Before doing anything else, make sure you reboot the modem/router and everything connected to it, including any wireless devices.

Windows Users
If you are a Windows user, you may download the claimit.exe file and run that on your PC. Just make sure you enter the IP Address for your Synology NAS and not the PC.

Download the claimit.exe file from here: ClaimPMS 205 and follow the instructions for How To Windows on the Wiki.

Mac & Linux Users
If you are using a Mac or Linux machine, you may download the claimpms.sh file and run that on your Mac or Linux machine. Just make sure you enter the IP Address for your Synology NAS and not the Mac or Linux machine.

Download the claimpms.sh file from here: ClaimPMS 204 and follow the instructions for How To Linux, Mac on the Wiki.

**Comment by ukdtom** [comment]
That's for internal connection to access the server, not for remote connections!

**Comment by ukdtom** [comment]
And sadly can't duplicate in any way :(
