### ISSUE TITLE
PMS Problem FATAL Error

### ISSUE THREAD

**Issue by rufo28** [ukdtom/ClaimIt#22]
This is the error below after using claimit in windows 10

![image](https://user-images.githubusercontent.com/53016920/70203399-e0c20400-172d-11ea-841d-6fef7d3d40be.png)

**Comment by ukdtom** [comment]
Make sure, that no firewall is blocking port 32400 on your PMS server

**Comment by ukdtom** [comment]
Ping.....Any results?

**Comment by ukdtom** [comment]
Closed due to lack of response
