### ISSUE TITLE
Getting 401 error from Plex

### ISSUE THREAD

**Issue by mustangthz** [ukdtom/ClaimIt#24]
plex.tv Username: <Redacted>

plex.tv Password:
plex.tv Password Repeated:
IP Address of PMS server: 127.0.0.1
Comparing entered passwords
Comparing entered passwords ok
Validating IP address
Getting PMS Server Identifier
Getting PMS Server Identifier ok
Getting User Token from plex.tv
Getting User Token from plex.tv ok
Getting PMS Claim Token
Getting PMS Claim Token ok
Claiming server
Fatal error happened
HTTP returned Status 401
blackops Plex Media Server #

**Comment by mustangthz** [comment]
Thank you very much for writing this script.  After some brute forcing I managed to claim my server, but there are some crazy 401 errors with linux servers on the latest releases.

**Comment by ukdtom** [comment]
https://github.com/ukdtom/ClaimIt/wiki/Errors-and-Troubleshooting#401
