### ISSUE TITLE
http returned status 401

### ISSUE THREAD

**Issue by somedudebob** [ukdtom/ClaimIt#25]
running this against a PMS docker container

host is ubuntu 16.04 (in the process of building a new one)

Have tried it using the host ip, container ip and loopback, all giving the same results.

plex.tv Password:
plex.tv Password Repeated:
IP Address of PMS server: 127.0.0.1
Comparing entered passwords
Comparing entered passwords ok
Validating IP address
Getting PMS Server Identifier
Getting PMS Server Identifier ok
Getting User Token from plex.tv
Getting User Token from plex.tv ok
Getting PMS Claim Token
Getting PMS Claim Token ok
Claiming server
Fatal error happened
HTTP returned Status 401

**Comment by ukdtom** [comment]
Read the manual!

https://github.com/ukdtom/ClaimIt/wiki/Errors-and-Troubleshooting

**Comment by somedudebob** [comment]
Yeah. I did. I removed the offending lines from the preferences xml, ran again no change

Then ssh tunnel to the host and opened a browser and can see the pms sitting there waiting to be claimed, tried to claim at that point with no luck also

**Comment by ukdtom** [comment]
Then PMS logs, in debug mode, right after reproducing, and logs in a zip file please

**Comment by ukdtom** [comment]
Closed due to lack of response
