### ISSUE TITLE
Error was:  The underlying connection was closed

### ISSUE THREAD

**Issue by ScrumpyCyder** [ukdtom/ClaimIt#26]
![Capture](https://user-images.githubusercontent.com/76046957/102211118-10702400-3ecb-11eb-9793-aae59eafb31a.PNG)

Running the windows version of ClaimIt. The full error message is:

The underlying connection was closed: An unexpected error occurred on a send

Running PMS via a docker container using Portainer on OMV 5 on a Raspberry Pi.

**Comment by ukdtom** [comment]
Hmmm.....Plex.tv doesn't wanna talk with you, so either a bad username/pwd, or older version of Windows that doesn't support TLS1.1

**Comment by ukdtom** [comment]
Closed due to lack of respose

**Comment by proimage** [comment]
I'm getting the exact same error:
![image](https://user-images.githubusercontent.com/1027523/115665016-53477a00-a34b-11eb-8357-f576a48abd5d.png)

Running Windows 10, with PMS running in a docker container on an unRAID box on my local network. The Windows machine IP is 10.0.0.19, and the unRAID box is at 10.0.0.10.

Should I open a new issue?

**Comment by ukdtom** [comment]
See here: https://github.com/ukdtom/ClaimIt/issues/27#issuecomment-778857644

**Comment by proimage** [comment]
The new executable got "stuck" for a while and then spit out this: 
![image](https://user-images.githubusercontent.com/1027523/115685275-c0193f00-a360-11eb-9dca-210af79ae58d.png)

**Comment by ukdtom** [comment]
As it says, see the wiki.

You either have a server that's already claimed, or a bad prefs file
https://github.com/ukdtom/ClaimIt/wiki/Errors-and-Troubleshooting

**Comment by proimage** [comment]
Doesn't look like that's the issue. I've reinstalled the entire container from scratch and let it generate the preferences.xml just in case. Ping works fine (although the initial response took about 10 seconds after pressing Enter, the `time=` values were all in the normal ~195ms range).

Any other ideas? FWIW, the PMS docker container allows specifying the `PLEX_CLAIM` variable:

![image](https://user-images.githubusercontent.com/1027523/115703978-70903e80-a373-11eb-9ebe-de5eafdb9471.png)

Could it be that the specified variable is conflicting with whichever one your app is trying to fetch? I know they supposedly only last for 4 minutes....

**Comment by ukdtom** [comment]
No idea, since not a docker dude....
But your DNS response was indeed too slow....
Try and switch to Google DNS as mentioned in the wiki

**Comment by proimage** [comment]
I've switched to Google's DNS, but still get the same error. :-/

**Comment by ukdtom** [comment]
Then please create a new issue, and on the forums, since not releated to the OP of this closed issue
