### ISSUE TITLE
"(" unexpected

### ISSUE THREAD

**Issue by ddec16** [ukdtom/ClaimIt#28]
Hi, 

Trying to run this on my linux server, getting the below error: 

`./claimpms.sh: 21: Syntax error: "(" unexpected
`

Permissions are set, not sure what else to do here.

**Comment by ddec16** [comment]
I literally just figured out the problem. Something is Cached on the Plex side, I changed my public IP and suddenly it works because Plex thinks its an entirely new server. This is killing me trying to figure out why, but at least its working now.

**Comment by trumpy81** [comment]
You can go to Plex Settings > Authorised Devices > All > Server and delete all but the most recent entry there to clear anything that is cached at plex.tv
