### ISSUE TITLE
Job aborted: getting plex.tv authentication token

### ISSUE THREAD

**Issue by mzuffolini** [ukdtom/ClaimIt#30]
I'm getting the error above. 
Also:

Error was: The request was aborted: Could not create SSL/TLS secure channel

Any idea? Thanks

**Comment by ukdtom** [comment]
More info needed, and sounds like you can't connect from the box towards plex.tv

**Comment by mzuffolini** [comment]
I'm running the exe from Windows 10 to claim a server on Synology 220+ with DSM7. Please let me know if you need further details

**Comment by ukdtom** [comment]
Please try this instead

https://www.dropbox.com/s/iqhwqpc7a3jut22/ClaimIt.exe?dl=0

Then report back

**Comment by mzuffolini** [comment]
I ended up having to reinstall anyway, and that fixed my issue. I appreciate your help though, thanks!

**Comment by stevehurcombe** [comment]
I'm getting this error too...
