### ISSUE TITLE
`ipAddress` string.Split() could use a comma :)

### ISSUE THREAD

**Issue by mm98** [ukdtom/ClaimIt#33]
I tried to use this tool earlier today. For some strange reason, on my Win11 the `ipAddress` entry was submitted with commas and not with periods, which made the app crash (separator must exist in `ipAddress`). It did show period in the UI. I had to download the source to add the following to make it work.

Added `comma` as a second separator on the string split.
```
int[] ipParts = ipAddress.Split(new String[] { ".", "," }, StringSplitOptions.RemoveEmptyEntries)
                                     .Select(s => int.Parse(s)).ToArray();
```

https://github.com/ukdtom/ClaimIt/blob/e9794997b15615d4d59de86a3942e553dec7228c/Windows/ClaimIt/Form1.cs#L278

**Comment by cremor** [comment]
The most likely problem is that the ip address box uses culture specific number separators. This already looks wrong in the UI. It should always use dots.

**Comment by ukdtom** [comment]
Windows version has been replaced with this one
https://github.com/ukdtom/ClaimPMS4Win/releases/latest
