### ISSUE TITLE
Linux -- ./claimpms.sh: 21: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by SilentDecode** [ukdtom/ClaimIt#34]
Downloaded the script for it's purpose to reclaim my server. 
I run it as root with the execute permission like it says in the wiki. 
And the error I get is:

root@plex01:/home/username# ./claimpms.sh
./claimpms.sh: 21: Syntax error: "(" unexpected
root@plex01:/home/username#

Nothing happens further. I have no further scripting knowledge to do something with it. The script was pasted from the 'raw' view on the file.

**Comment by ejola** [comment]
I'm having the same issue and similarly little scripting knowledge, so take with a grain of salt.

Based on a few searches, it seems like an implicit difference in scripting shells. It seems like it's written for bash, but it's being set up to run in sh. Try replacing the first line with 
`#!/bin/bash`

Hopefully this helps you; I have sh on my server but not bash, so I'm working getting bash now.

**Comment by ukdtom** [comment]
Please read the Wiki ;)

https://github.com/ukdtom/ClaimIt/wiki/Errors-and-Troubleshooting#21-syntax-error

**Comment by trumpy81** [comment]
Tommy, check your gmail :)
