### ISSUE TITLE
[Bug] Latest Version crashes in Win11

### ISSUE THREAD

**Issue by trumpy81** [ukdtom/ClaimIt#35]
I tried to run the latest version but it crashes when I try to open it.

The error is shown below:
![image](https://user-images.githubusercontent.com/12381786/188945953-ac979407-0f54-49c2-ae2f-9cca74b0d8fc.png)

There seems to be an issue with Windows.forms detecting PMS in
D:\repos\UKDTOM\ClaimPMS4Win\ClaimPMS4Win\Form1.cs:line 47.

Edit: It appears to run in a Win10 VM but I have no Plex server in the VM, so it fails to authenticate etc.

I added a PMS server to the VM and ClaimPMS4Win now crashes with the same error as shown on Win 11 above.

Edit 2: After making sure PMS in the Win10 VM was already signed in and Plex had finished site maintenance, ClaimPMS4Win worked as shown below:

![image](https://user-images.githubusercontent.com/12381786/188954468-f0bebd90-314f-4546-85cb-d5bc239b880a.png)

It still crashes in Win 11 though, but if I click on the continue button in the crash dialogue, it runs properly and claims etc as shown in Win10VM image above.

Running ClaimPMS4Win a second time in Win 11, now shows below without any crash dialogue:

![image](https://user-images.githubusercontent.com/12381786/188956284-9031e6df-c2f4-453a-a306-0190bd1eb4df.png)

Win10 VM also shows the above when run a second time.

**Comment by ukdtom** [comment]
Heh, wrong repo, but nice catch

I made a new release in the right repo:

https://github.com/ukdtom/ClaimPMS4Win/releases/latest

And FYI, I'll be away until Tuesday for a mini vacation

**Comment by trumpy81** [comment]
I thought I was in the right repo as this is where the link lead me ... lol

Installed the new release and it appears to be working correctly now.

See you when you get back :)
