### ISSUE TITLE
Wiki transfer ?

### ISSUE THREAD

**Issue by ukdtom** [ukdtom/ClaimIt#36]
Hi there @trumpy81 

If possible, and if time, you have an invite to https://github.com/ukdtom/ClaimPMS4Win pending

And if accepting, maybe pass the parts of the Wiki that's still relevant to that project?

And also go through this Wiki, and make sure it ref. the new repo when we talk about Wiki ?

**Comment by trumpy81** [comment]
Wiki created and updated.
