### ISSUE TITLE
Claimit script doesn't handle 2FA

### ISSUE THREAD

**Issue by chris-fp** [ukdtom/ClaimIt#37]
I've just tried to use this script as my IP addressing is public and not private although quite why using public is an issue is beyond me but I digress...

username and password are correct and I use 127.0.0.1 as per the instructions but I get below:-

IP Address of PMS server: 127.0.0.1
Comparing entered passwords
Comparing entered passwords ok
Validating IP address
Getting PMS Server Identifier
Getting PMS Server Identifier ok
Getting User Token from plex.tv
******** ERROR ********
We failed to authenticate towards plex.tv
Please check username and password, as well as network access

I recently added 2FA to my Plex account after the password breach problem and it appears that this script was written before 2FA was available so it won't handle any 2FA responses.

Don't suppose anybody from Plex is looking to update this script?

**Comment by trumpy81** [comment]
Unfortunately, Tommy is on holiday for the next few days, so he will not respond until after he returns home.

The script was written and updated approx. 3 or 4 years ago and, if I recall correctly, that pre-dates 2FA for Plex.

As an alternative, if you can fire up a Windows VM in Linux and then run ClaimPMS4Win, it does support 2FA authentication and will claim your Plex Media Server/s.

See the [ClaimPMS4Win Wiki](https://github.com/ukdtom/ClaimPMS4Win/wiki) for more details.

**Comment by chris-fp** [comment]
You'd just build another server if that happened.

Anyway - I changed the way the docker networking worked (bridge instead of host) and re-ran the script*, inside the docker image,  using the docker IP address as the server address and that worked. I can now progress with testing.

*temporarily turned off 2FA on my account to do this. If Tommy could amend the script that would help non-windows users going forward as you cannot run the windows version within a docker image !

**Comment by ukdtom** [comment]
When using 2FA, do like this:

Pwd: secret
2FA: 1234

When asked for Pwd, enter secret1234
