### ISSUE TITLE
error in function Getting PMS Server Identifier

### ISSUE THREAD

**Issue by mikkel2326** [ukdtom/ClaimIt#39]
Howdy:
Cool program.  Trying to claim my plex server on Drobo 5N.  Can't figure out why this error is throwing.  I've installed curl via DroboPorts.  Running the script on the Drobo itself utilizing 127.0.0.1 .  The server is running.

./claimpms.sh: line 219: curl: not found
******** ERROR ********
We failed to get the Plex Media Server ID
Please check server is up and running, as well as the IP address entered

**Comment by trumpy81** [comment]
I suspect your Drobo may be missing the curl package or it is not configured correctly.

You may run the file from your PC/Laptop.

If you use a Windows PC then see this Wiki: https://github.com/ukdtom/ClaimPMS4Win/wiki

Run the script in Terminal and when asked, enter the IP address of your Drobo/PMS
**E.G.** 192.168.0.22

Also, see the Wiki for more information about running the script file and troubleshooting tips. The Wiki button is up there ^ at the top of the page.

You may of course, open Plex/Web > Settings > General and click on the Claim Server button beside your username/email address.

Let me know if that helps please.

**Comment by mikkel2326** [comment]
Thank you for the quick response. I suspect you are right. I need to educate my self on cross compiling.

I will also look at the windows solution. The plex server is running on the Drobo with a non IPV4 address: 192.169.x.x. . Any way to redirect the Drobo up to use 127.0.0.1 in Windows?

Thank you again

**Comment by trumpy81** [comment]
The only way that will work from your PC/Laptop would be to change the IP address to an RFC1918 compliant address, otherwise it will fail.

You could possibly try an SSH Tunnel, see the bottom of this page: https://support.plex.tv/articles/200288586-installation/ for details.

I would recommend using PuTTY for the SSH Tunnel if you are running on Windows.

If you run Windows, then ClaimPMS4Win would be the way to go. It is much easier and by all accounts more reliable.

Give it a whirl, it wont cost you anything ... lol

**Comment by mikkel2326** [comment]
Update: I was able to create the tunnel with putty. logged into the plex server. Tried to claim the server via the settings. The claim server button processes for a few moments and returns. The message is the same "This server is unclaimed and not secure" Still tinkering. Thanks for your help.

Michael

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ukdtom** [comment]
Sadly, since nu curl found, Drobo is not supported.

I can only recommend you try the Plex Forums

**Comment by mikkel2326** [comment]
Hey Tommy:
I found that curl wasn't in my path. Curl works now but I am now getting the following error:

plex.tv Username: ***@***.***

plex.tv Password:
plex.tv Password Repeated:
IP Address of PMS server: 127.0.0.1
Comparing entered passwords
Comparing entered passwords ok
Validating IP address
Getting PMS Server Identifier
Getting PMS Server Identifier ok
Getting User Token from plex.tv
******** ERROR ********
We failed to authenticate towards plex.tv
Please check username and password, as well as network access

With the tunnel, my plex server is at 127.0.0.1:8888. Does that change anything? I am tunneled through Putty. If I navigate to http://127.0.0.1:8888/web, the plex web client comes up. I am still unable to claim the server. Any thoughts?

Michael

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ukdtom** [comment]
Reopened ;)

And sadly on my part, since I need to find time to merge PR's

Download this version of the script:
https://github.com/ukdtom/ClaimIt/blob/passencode-fix/linux/claimpms.sh

And if using 2FA auth. do the following:

You have a password as MyPwd
You have a 2FA code as 123456

When asked for password, enter MyPwd123456

**Comment by mikkel2326** [comment]
Thanks Tommy. Well, I tried the revised script and the result is the same utilizing 127.0.0.1. my server comes up and is active at 127.0.0.1:8888. I can ping 8.8.8.8. In fact, it is the same result if I don't put a uid and pw at the prompts. i'm not using 2FA auth. I'm thinking of changing the IP range from the 192.169.x.x to a 192.168.x.x type of situation. Maybe that'll work.

Michael

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by ukdtom** [comment]
192.169.x.x

Wow...Didn't spot that, and above is NEVER advised for a private network!

When said, when running the script directly on your NAS, when asked for an IP address, you should use 127.0.0.1

**Comment by ukdtom** [comment]
And since not having a Drobo box, clueless :(

**Comment by mikkel2326** [comment]
Okay. Good news. I have successfully claimed the Plex Server on my Drobo--fossil that it is.

I changed my network IP on the router from 192.169.x.x to 192.168.x.x.

I uninstalled Plex from my Drobo and reinstalled it using Drobo Dashboard (an app that allows you to administrate the Drobo-- set up shares, install apps, etc.).

I then able to start up the Plex Server utilizing the Dashboard and claim the server.

I upgraded the Plex App as prompted utilizing the Dashboard.

Thought all was well and good but was greeted with the message from my Roku that the Drobo Plex Server was too old to be utilized.

Went to Plex.TV. Got the latest plex.tgz for the Drobo and upgraded manually. A simple drag and drop to the DroboApps directory and restarted the Drobo.

Went back to the Roku and I was golden. Everything is working great! The ARM processor of the Drobo is pretty anemic, but is works well enough.

Thank you for your responsiveness and help. Please close the ticket.

Michael

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
