### ISSUE TITLE
HTTP 500 Error, Fresh Install

### ISSUE THREAD

**Issue by lindraden** [ukdtom/ClaimIt#40]
Installed plexmediaserver on my raspberry pi 4 recently and I've never had this issue before where it didn't claim the name when I had it setup on my raspberry pi 2. Same with setting it up on my Windows PC (didn't want to keep running it off my PC).

It's a complete fresh install. I've even uninstalled it, removed the directory, reinstalled it, rebooted the pi. Running the script with both 127.0.0.1 and the IP of the Pi (wired). DNS of the Pi is set to 8.8.8.8 and nslookup confirms that.
Have not touched Preferences.xml.

Any other ideas?

**Comment by spectrius** [comment]
Could be related to this, a lot of people are having issues claiming right now

https://forums.plex.tv/t/cannot-claim-server-unprocessable-entity/822888/8

**Comment by ukdtom** [comment]
What @spectrius says, and Plex is currently looking into it
