### ISSUE TITLE
I'm unable to claim the server despite I run the script

### ISSUE THREAD

**Issue by emasaba** [ukdtom/ClaimIt#42]
Plex Version: 1.40.0.7998
Latest ClaimIt version.

I'm unable to claim the server. 
I tried ClaimIt, but it doesn't work (got error:500 and all fixes doesn't work to me)

I also tried reinstalling Plex a lot of times but still nothing.

It also says to update the server, but at least the OS doen't find any new update for it (so far i always updated it via OMV or directly via command line)

**Comment by ukdtom** [comment]
Please see error 500 here:

https://github.com/ukdtom/ClaimIt/wiki/Errors-and-Troubleshooting

**Comment by emasaba** [comment]
I already checked there, and tried almost all fixes provided, but nothing.

**Comment by ukdtom** [comment]
Then please make a post on the Plex forums, since it's the media server that returns the 500 error code
