### ISSUE TITLE
We failed to authenticate towards plex.tv

### ISSUE THREAD

**Issue by salutdiego** [ukdtom/ClaimIt#6]
Hi, i'm running on Synology DS214+ DSM 6.2 PLEX 1.13.4.5271-200287a06

I test 127.0.0.1 and also 192.168.1.51, same result same error
i also test my login and password by loging off an loging on from the page http://192.168.1.51:32400/web/index.html# (myplexemail@gmail.com)

Comparing entered passwords
Comparing entered passwords ok
Getting PMS Server Identifier
Getting PMS Server Identifier ok
Getting User Token from plex.tv
******** ERROR ********
We failed to authenticate towards plex.tv
Please check username and password, as well as network access

How can i pass this ?

Regards,

salutdiego

**Comment by ukdtom** [comment]
I assume you are running it directly from your Synology box in a script?

If so, then it most likely is something that is preventing your Synology box from reaching plex.tv, like a bad DNS setup, or default router

**Comment by salutdiego** [comment]
i give up, i switch to dlna+filebot+shell script
