### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by dominicgetdown** [ukdtom/ClaimIt#9]
Getting Can't Claim PMS... Job Aborted
Error Was: remote server returned error (500)

Running plex on freenas.  This is from the windows claimit.   Should I use the other one instead?

**Comment by dominicgetdown** [comment]
![Capture](https://user-images.githubusercontent.com/8095535/56099956-76233600-5ec8-11e9-84f5-ce2722f5ae1b.PNG)

**Comment by dominicgetdown** [comment]
![Capture1](https://user-images.githubusercontent.com/8095535/56099959-80453480-5ec8-11e9-83ab-456cc72a1362.PNG)

**Comment by ukdtom** [comment]
Internal error can be everything, since that's an internal server error from PMS!

Suggest you for a start, run the bach script directly on the PMS host, and use 127.0.0.1 as the IP Addy when prompted

**Comment by dominicgetdown** [comment]
Not sure how to do that.  This is my first time using freenas and not sure how to run a bach script.  Is there a tutorial on how to do that?

**Comment by dominicgetdown** [comment]
You can close this ticket.  The issue was that plex's static IP was inside the DHCP range of my router.  Moved the IP of plex outside of that range and now it works.  Thanks
